repos:
  - repo: https://github.com/semgrep/pre-commit
    rev: 'v1.46.0'
    hooks:
      - id: semgrep
        name: Semgrep Security Check
        entry: semgrep
        args: ['--config', '.semgrep.yml', '--error']
        stages: [commit]
