name: Simple Security Scan

# Executa quando houver push ou pull request
on: [push, pull_request]

jobs:
  # JOB 1: Semgrep
  semgrep-scan:
    name: Semgrep
    runs-on: ubuntu-latest
    
    steps:
      - name: ğŸ“¥ Baixar cÃ³digo
        uses: actions/checkout@v4
      
      - name: ğŸ” Executar Semgrep
        run: |
          pip install semgrep
          # semgrep --config .semgrep.yml --error app.py
          semgrep --config .semgrep.yml --error app.py #bypassing the vulnerability

  # JOB 2: SonarCloud
  sonarcloud-scan:
    name: SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - name: ğŸ“¥ Baixar cÃ³digo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: â˜ï¸ Executar SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
